#!/bin/bash

######################################################################
#               VPS - Command Line Interface                         #
#                                                                    #
#               Author: HIEUDT                                       #
######################################################################

SCRIPT_URL="https://raw.githubusercontent.com/RootOfGenius/vps-cli/main/bin/vps-cli"

# VPS Info
OS_VER=$(lsb_release -rs)
USER_COMMAND=$(id -u)

# LANG
ROOT_ERR="Ban can chay script voi user root. Chay lenh \"sudo su\" de co quyen root! hoac sudo bash install"
COMPATIBLE="VPS-CLI chi ho tro cac he dieu hanh: Ubuntu 16.04"
CANCEL_INSTALL="Huy cai dat..."
OS_WRONG="Script chi hoat dong tren \"Ubuntu 20\"!"
SETUP_SUCCESS="Cai dat hoan tat! vui long su dung lenh vps-cli de mo menu!"

# Set Color
RED='\033[0;31m'
GREEN='\033[0;32m' 
NC='\033[0m'


###################
#Check conditions #
###################

# Check if user not root
checkRoot () {
    if [[ "$USER_COMMAND" != "0" ]]; then
        printf "${RED}%s${NC}\n" "${ROOT_ERR}"
        printf "${RED}%s${NC}\n" "${CANCEL_INSTALL}"
        exit
    fi
}

checkOs () {
    if [ "$OS_VER" != "16.04" ]; then
	    printf "${RED}%s${NC}\n" "$COMPATIBLE"
        printf "${RED}%s${NC}\n" "${CANCEL_INSTALL}"
    	exit
    fi
}

initRequireCheck(){
    echo ""
    checkRoot
    checkOs
}

installRequirement() {
    rm -f /etc/localtime
    ln -sf /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime
    apt-get install curl -y
}

initial(){
    clear
    printf "========================================================\n"
    echo   "             VPS - Command Line Interface              "
    echo   "            Auto Install TechStack on Ubuntu           "
    echo   "                   From HieuDT with <3                 "
    printf "========================================================\n"
    echo ""
    echo "Loading..."
    sleep 2
}

setup() {
    rm -rf /bin/vps-cli
    wget -q $SCRIPT_URL -O /bin/vps-cli && chmod +x /bin/vps-cli
    rm index.html

    clear
    printf "========================================================\n"
    echo   "             VPS - Command Line Interface              "
    echo   "            Auto Install TechStack on Ubuntu           "
    echo   "                   From HieuDT with <3                 "
    printf "========================================================\n"
    echo ""
    printf "${GREEN}%s${NC}\n" "${SETUP_SUCCESS}"
    sleep 2
    exit
}


initial
initRequireCheck
installRequirement
setup